### ISSUE TITLE
Bug with "TTL value is empty"?

### ISSUE THREAD

**Issue by shakalandy** [axelhahn/cronwrapper#14]
First of all, thanks @axelhahn for this great and useful wrapper!
We're testing that one now together with monitoring via the icinga2 script.

We noticed that some check attempts fail on a simple laravel/php cronjob configured like this in /etc/cron.d/test-wrapper:

```
* * * * * www-data /opt/cronwrapper/cronwrapper.sh 5 "php8.2 /var/www/test-app/current/artisan schedule:run" testtag
```    

Sometimes "cronstatus" seems to have problems with the TTL, as it reports the "TTL value as empty":

```
 command   : 
    last start: 
    returncode: 0 OK
    duration  : 185 s
    ttl       : ERROR: ttl value is empty
    expires   : 0 1970-01-01 00:00:00 <<<<<<<<<< ERROR
    CHECK FAILED
```

With the next run, it's ok again.
Any Idea on what's happening here?
Sometimes the job is running longer than 1 minute, that's why the TTL is set to 5 (minutes) and not 1 or 2.

Thanks very much!

**Comment by axelhahn** [comment]
Hi @shakalandy 
sorry for the late response :-/ And thanks for reporting this. 

The cronstatus.sh script loops over the created logs in /var/tmp/cronlogs/.
The current running job writes into a file `NAME.log.running` and is renamed into `NAME.log` if it is finished.
It searches for a value "SCRIPTTTL" in the *.log (=last finished job) - and the error occurs if it does not exist.

At the moment I must say, I need to verify this. It sounds to occur on jobs starting each minute but sometimes run longer 60 sec.

Remarks: 
(1)
The last update prevents the execution of a 2nd job if the last started job is still running.
https://www.axel-hahn.de/docs/cronwrapper/Configuration.html
set SINGLEJOB to 0 to keep the former behaviour.

(2)
FYI: My Icinga check script is here:
https://git-repo.iml.unibe.ch/iml-open-source/icinga-checks/-/blob/master/check_cronstatus

**Comment by axelhahn** [comment]
What I see in the code:
If there are 2 instances of the same job. One finishes and moves the *.log.running into *.log. The still running job starts to write into an empty *.log.running and on its exit it moves *log.running into *.log
Now the *log it does not have the line with SCRIPTTTL=... in it and the described error occurs.

Workaround is: update the cronwrapper using git pull. It prevents multiple execution of the same job.

I can fix it by another naming of the log file of a running job (eg. using a PID in the filename). Additionally I would add a check of "dead" logfiles in the cronstatus.

**Comment by axelhahn** [comment]
MR https://github.com/axelhahn/cronwrapper/pull/17/

**Comment by shakalandy** [comment]
Thanks for the update @axelhahn!

I found out that using a "tag" for the job somehow works as a workaround for the "missing TTL" problem.
Will try with the new version.

Thanks for adding SINGLEJOB option as well, pretty cool!

**Comment by axelhahn** [comment]
Hi @shakalandy 

I merged the branch into the master branch today. You can update with git pull. I will roll it out on 100+ servers today. 

The fix is: each starting job creates a log with a PID in the filename. The cronstatus.sh got an update too to detect logs of still running or aborted jobs.
Please tell me if it works properly on your side.

Schönen Abend!
Axel

**Comment by shakalandy** [comment]
Hi @axelhahn,

thanks for the update!

Using recent version I still can manage to run 2 jobs at the same time (using default config, where SINGLEJOB=1).
I first thought, that the "tag" I'm using is the problem.

Started two jobs in console now, this is the set -x output of the second job, which runs parallel with the same parameters:
Does this help?

```
root@backup01:~# /opt/cronwrapper/cronwrapper.sh 5040 "/usr/local/bin/remote-s3sync"
+ _version=1.25
+ line1=--------------------------------------------------------------------------------
+ typeset -i TTL=5040
+ CALLSCRIPT=/usr/local/bin/remote-s3sync
+ LABELSTR=
+ LOGFILE=/tmp/call_any_script_3670852.log
+ test -z ''
++ basename /usr/local/bin/remote-s3sync
++ cut -f 1 -d ' '
+ LABELSTR=remote-s3sync
+ LABELSTR=remote-s3sync
+ TOUCHPART=_flag-remote-s3sync_expire_
+ LOGDIR=/var/tmp/cronlogs
++ hostname -f
+ MYHOST=backup01.servers.example.com
+ JOBBLOGBASE=backup01.servers.example.com_joblog_
+ SINGLEJOB=1
++ dirname /opt/cronwrapper/cronwrapper.sh
+ test -f /opt/cronwrapper/cronwrapper.env
++ dirname /opt/cronwrapper/cronwrapper.sh
+ test -f /opt/cronwrapper/cronwrapper.cfg
++ dirname /opt/cronwrapper/cronwrapper.sh
+ . /opt/cronwrapper/inc_cronfunctions.sh
++ typeset -i rc=0
++ typeset -i rcAll=0
++ export CW_timer_start
++ export CW_lockfile
+++ date +%s.%N
++ CW_timer_start=1689933323.527566549
+++ cw._getlockfilename '/opt/cronwrapper/cronwrapper.sh 5040 /usr/local/bin/remote-s3sync'
+++ echo /tmp/_lock___opt_cronwrapper_cronwrapper_sh_5040__usr_local_bin_remote_s3sync
++ CW_lockfile=/tmp/_lock___opt_cronwrapper_cronwrapper_sh_5040__usr_local_bin_remote_s3sync
+ FINALOUTFILE=/var/tmp/cronlogs/backup01.servers.example.com_remote-s3sync.log
++ date +%a
+ JOBLOG=/var/tmp/cronlogs/backup01.servers.example.com_joblog_Fri.done
+ OUTFILE=/var/tmp/cronlogs/backup01.servers.example.com_remote-s3sync.log.running.3670852
+ typeset -i iStart
++ date +%s
+ iStart=1689933323
+ '[' 5040 = '-?' ']'
+ '[' 5040 = -h ']'
+ '[' 5040 = --help ']'
+ '[' 2 -lt 2 ']'
+ '[' 5040 -eq 0 ']'
+ '[' -z backup01.servers.example.com ']'
+ mkdir /var/tmp/cronlogs
+ chmod 777 /var/tmp/cronlogs
+ test -f /var/tmp/cronlogs/backup01.servers.example.com_remote-s3sync.log.running.3670852
+ rm -f /var/tmp/cronlogs/backup01.servers.example.com_remote-s3sync.log.running.3670852
+ touch /var/tmp/cronlogs/backup01.servers.example.com_remote-s3sync.log.running.3670852
+ w 'REM --------------------------------------------------------------------------------'
+ echo 'REM --------------------------------------------------------------------------------'
+ w 'REM CRON WRAPPER - backup01.servers.example.com'
+ echo 'REM CRON WRAPPER - backup01.servers.example.com'
+ w 'REM --------------------------------------------------------------------------------'
+ echo 'REM --------------------------------------------------------------------------------'
+ w SCRIPTNAME=/usr/local/bin/remote-s3sync
+ echo SCRIPTNAME=/usr/local/bin/remote-s3sync
+ w SCRIPTTTL=5040
+ echo SCRIPTTTL=5040
++ date '+%Y-%m-%d %H:%M:%S'
+ w 'SCRIPTSTARTTIME=2023-07-21 11:55:23, 1689933323'
+ echo 'SCRIPTSTARTTIME=2023-07-21 11:55:23, 1689933323'
+ w SCRIPTLABEL=remote-s3sync
+ echo SCRIPTLABEL=remote-s3sync
+ w SCRIPTPROCESS=3670852
+ echo SCRIPTPROCESS=3670852
+ '[' -z /usr/local/bin/remote-s3sync ']'
+ w REM --------------------------------------------------------------------------------
+ echo 'REM --------------------------------------------------------------------------------'
+ typeset -i iExpire
++ date +%s
+ iExpire=1689933323
+ typeset -i iExpDelta=7560
+ '[' 7560 -gt 60 ']'
+ iExpDelta=60
+ iExpire=1690239323
+ '[' 5040 -eq 0 ']'
+ aLastfiles=("${LOGDIR}"/*"${TOUCHPART}"*)
+ lastfile=/var/tmp/cronlogs/_flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
+ ls /var/tmp/cronlogs/_flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
++ basename /var/tmp/cronlogs/_flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
+ TOUCHFILE=_flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
+ typeset -i expdate
++ echo _flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
++ cut -f 4 -d _
+ expdate=1690239294
++ echo _flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
++ cut -f 5 -d _
+ runserver=backup01.servers.example.com
++ date -d @1690239294
+ w 'REM INFO: expires 1690239294 - Tue Jul 25 12:54:54 AM CEST 2023'
+ echo 'REM INFO: expires 1690239294 - Tue Jul 25 12:54:54 AM CEST 2023'
+ typeset -i timeleft=1690239294-1689933323
+ echo backup01.servers.example.com
+ grep -F backup01.servers.example.com
+ rm -f /var/tmp/cronlogs/_flag-remote-s3sync_expire_1690239294_backup01.servers.example.com
+ touch /var/tmp/cronlogs/_flag-remote-s3sync_expire_1690239323_backup01.servers.example.com
+ w JOBEXPIRE=1690239323
+ echo JOBEXPIRE=1690239323
+ w REM --------------------------------------------------------------------------------
+ echo 'REM --------------------------------------------------------------------------------'
+ rc=none
+ eval /usr/local/bin/remote-s3sync

```

Am i doing something wrong? Don't think so, or?

**Comment by axelhahn** [comment]
I see the reason. The SINGLEJOB option was introduced the version before and was broken now because renamed the output for a process to a uniq filename. This line can't be true anymore:
https://github.com/axelhahn/cronwrapper/blob/master/cronwrapper.sh#L177
I must use a globbing to test outputfiles of other processes.

**Comment by axelhahn** [comment]
I think it is fixed in
https://github.com/axelhahn/cronwrapper/pull/18


My test:
(1)
I set `SINGLEJOB=1` in cronwrapper.cfg

(2)
In one terminal I started:
`./cronwrapper.sh 10 "sleep 100 && ls -l" sleeper`

(3)
In a 2nd one aomething with much less sleep time:
`./cronwrapper.sh 10 "sleep 10 && ls -l" sleeper`
...which stops immediately (and doesn't sleep 10 sec).


Reverse test:

I set `SINGLEJOB=0` in cronwrapper.cfg

Now when starting 
`./cronwrapper.sh 10 "sleep 100 && ls -l" sleeper`
and 
`./cronwrapper.sh 10 "sleep 10 && ls -l" sleeper`
in different terminals ... then both jobs run.


Additionally I changed the logging behaviour of blocked jobs. Those do not generate a logfile anymore (in /var/tmp/cronlogs/). This MAYBE could generate a lot of files that must be deleted manually what is not useful.

But blocked jobs leave an entry in the joblog now. They get returncode 1 and `blockingpid=...`.

```txt
# cat /var/tmp/cronlogs/linux-pc_joblog_Fri.done
...
job=sleeper:host=linux-pc:start=1689973797:end=1689973797:exectime=0:ttl=10:rc=1:blockingpid=12772
```

Grep for `blockingpid=` to see how often jobs were blocked.

**Comment by shakalandy** [comment]
Thanks @axelhahn - Can confirm that it's now working as expected - cool!

Great job 👏

**Comment by axelhahn** [comment]
@shakalandy  thanks for your feedback! I just updated the docs in https://www.axel-hahn.de/docs/cronwrapper/ and can close the issue now.
Feel free to communicate features and wishes too.
